<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

return [
    'CATEGORY_ALIAS' => 'Псевдоним',
    'CATEGORY_CREATED_TIME' => 'Время создания',
    'CATEGORY_CREATED_USER_ID' => 'Создатель',
    'CATEGORY_DESCRIPTION' => 'Описание',
    'CATEGORY_LANGUAGE' => 'Язык',
    'CATEGORY_LEVEL' => 'Вложенность',
    'CATEGORY_METADATA' => 'Metadata',
    'CATEGORY_MODIFIED_TIME' => 'Время изменения',
    'CATEGORY_MODIFIED_USER_ID' => 'Изменил',
    'CATEGORY_PARAMS' => 'Параметры',
    'CATEGORY_PARENT_ID' => 'Родитель',
    'CATEGORY_PATH' => 'Путь',
    'CATEGORY_PUBLISHED' => 'Опубликовано',
    'CATEGORY_TITLE' => 'Заголовок',
    'ID' => 'ID',
    'CATEGORY_PAGE_TITLE' => 'Категории',
    'CATEGORY_CREATE' => 'Создать категорию',
];
