<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'MENU_CREATED_TIME' => 'Время создания',
    'MENU_CREATED_USER_ID' => 'Создатель',
    'ID' => 'ID',
    'MENU_LANGUAGE' => 'Язык',
    'MENU_MODIFIED_TIME' => 'Время изменения',
    'MENU_MODIFIED_USER_ID' => 'Изменил',
    'MENU_PUBLISHED' => 'Опубликовано',
    'MENU_TITLE' => 'Заголовок',
    'MENU_PAGE_TITLE' => 'Меню',
    'MENU_PAGE_CREATE' => 'Создать меню',
];
