<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ACTIVITY_KIND' => 'Activity Kind',
    'ADDITIONAL_EQUIPMENT' => 'Additional Equipment',
    'ADDITIONAL_FILES' => 'Additional Files',
    'ADDRESS' => 'Address',
    'ALIAS' => 'Alias',
    'BRANCHES' => 'Branches',
    'CATEGORY_ID' => 'Category ID',
    'CATEGORY_SELECT_PARENT' => 'Select category ...',
    'CODE' => 'Code',
    'CONTACT_PERSON' => 'Contact Person',
    'CREATED_TIME' => 'Created Time',
    'CREATED_USER_ID' => 'Created User ID',
    'DESCRIPTION' => 'Description',
    'FEATURED' => 'Featured',
    'FULLNAME' => 'Fullname',
    'HITS' => 'Hits',
    'ID' => 'ID',
    'IMAGES' => 'Images',
    'LANGUAGE' => 'Language',
    'LOGO' => 'Logo',
    'MAIL' => 'Mail',
    'MANUFACTURER_ID' => 'Manufacturer ID',
    'MANUFACTURER_LINK' => 'Manufacturer Link',
    'MANUFACTURER_SELECT' => 'Select manufacturer ...',
    'METADATA' => 'Metadata',
    'MODIFIED_TIME' => 'Modified Time',
    'MODIFIED_USER_ID' => 'Modified User ID',
    'ORDERING' => 'Ordering',
    'PARENT_ID' => 'Parent ID',
    'PHONE' => 'Phone',
    'PUBLISHED' => 'Published',
    'SHORTNAME' => 'Shortname',
    'SITE' => 'Site',
    'SOCIAL_NETWORKS' => 'Social Networks',
    'SPECIFICATIONS' => 'Specifications',
    'TITLE' => 'Title',
    'VIDEO_LINK' => 'Video Link',
];
