<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CATEGORY_ALIAS' => 'Alias',
    'CATEGORY_CREATED_TIME' => 'Created time',
    'CATEGORY_CREATED_USER_ID' => 'Created user ID',
    'CATEGORY_DESCRIPTION' => 'Description',
    'CATEGORY_LANGUAGE' => 'Language',
    'CATEGORY_LEVEL' => 'Level',
    'CATEGORY_METADATA' => 'Metadata',
    'CATEGORY_MODIFIED_TIME' => 'Modified time',
    'CATEGORY_MODIFIED_USER_ID' => 'Modified user ID',
    'CATEGORY_PARAMS' => 'Parameters',
    'CATEGORY_PARENT_ID' => 'Parent ID',
    'CATEGORY_PATH' => 'Path',
    'CATEGORY_PUBLISHED' => 'Published',
    'CATEGORY_TITLE' => 'Title',
    'ID' => 'ID',
    'CATEGORY_PAGE_TITLE' => 'Categories',
    'CATEGORY_CREATE' => 'Create category',
    'CATEGORY_SELECT_PARENT' => 'Select parent ...',
    'CATEGORY_PARENT_ERROR' => 'Error on parent category check',
    'CATEGORY_USER_ERROR' => 'Error on user check',
    'CATEGORY_NOT_MODIFY' => 'Material not modify yet'
];
