<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    
    'ALIAS' => 'Alias',
    'SURE_TO_DELETE' => 'Are you sure you want to delete this item?',
    'CAT_ID' => 'Category',
    'CREATE_JOURNAL' => 'Create a journal entry',
    'CREATE_KNOWLEDGE_BASE' => 'Create article',
    'CREATE_KNOWLEDGE_BASE_CATEGORY' => 'Create knowledge base category',
    'CREATED_TIME' => 'Created time',
    'CREATED_USER_ID' => 'Created user',
    'DATE' => 'Date',
    'DELETE' => 'Delete',
    'DESCRIPTION' => 'Description',
    'FEATURED' => 'Featured',
    'FULLTEXT' => 'Full text',
    'HITS' => 'Hits',
    'ID' => 'ID',
    'IMAGE' => 'Image',
    'IMAGES' => 'Images',
    'INTROTEXT' => 'Intro text',
    'JOURNALS' => 'Journals',
    'KNOWLEDGE_BASE_CATEGORIES' => 'Categories',
    'KNOWLEDGE_BASES' => 'Articles',
    'LANGUAGE' => 'Language',
    'LEVEL' => 'Lavel',
    'METADATA' => 'Metadata',
    'MODIFIED_TIME' => 'Modifed time',
    'MODIFIED_USER_ID' => 'Modifed user',
    'NOT_MODIFY' => 'Material not modify yet',
    'ORDERING' => 'Ordering',
    'OPEN_MATERIAL' => 'Открыть материал',
    'PARAMS' => 'Parameters',
    'PARENT_ERROR' => 'Error on parent category check',
    'PARENT_ID' => 'Parent category',
    'PATH' => 'Path',
    'PUBLISHED' => 'Published',
    'RESET' => 'Reset',
    'SAVE' => 'Save',
    'SEARCH' => 'Search',
    'PAGE_DOES_NOT_EXIST' => 'The requested page does not exist.',
    'TITLE' => 'Title',
    'UPDATE' => 'Update',
    'USER_ERROR' => 'Error on user check',
    'UPDATE_JOURNAL' => 'Update Journal entry: {name}',
    'UPDATE_KNOWLEDGE_BASE_CATEGORY' => 'Update Knowledge Base Category: {name}',
    'UPDATE_KNOWLEDGE_BASE' => 'Update Knowledge Base Article: {name}',
];
