<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ARTICLE_CAT_ID' => 'Категория',
    'ARTICLE_CREATED_TIME' => 'Время создания',
    'ARTICLE_CREATED_USER_ID' => 'Создатель',
    'ARTICLE_FEATURED' => 'Избранное',
    'ARTICLE_FULLTEXT' => 'Текст',
    'ARTICLE_HITS' => 'Показы',
    'ID' => 'ID',
    'ARTICLE_IMAGES' => 'Изображения',
    'ARTICLE_INTROTEXT' => 'Анонс',
    'ARTICLE_LANGUAGE' => 'Язык',
    'ARTICLE_METADATA' => 'Metadata',
    'ARTICLE_MODIFIED_TIME' => 'Время изменения',
    'ARTICLE_MODIFIED_USER_ID' => 'Изменил',
    'ARTICLE_ORDERING' => 'Сортировка',
    'ARTICLE_PATH' => 'Путь',
    'ARTICLE_PUBLISHED' => 'Опубликовано',
    'ARTICLE_TITLE' => 'Заголовок',
    'ARTICLE_PAGE_TITLE' => 'Материалы',
    'ARTICLE_PAGE_TAGS' => 'Тэги',
    'ARTICLE_CREATE' => 'Создать материал',
    'ARTICLE_CAT_SELECT' => 'Выберите категорию ...',
    'ARTICLE_FILE_DELETED' => 'Файл удален',
    'ARTICLE_OPEN_MATERIAL' => 'Открыть материал',
    'SELECT_TAGS' => 'Укажите тэги',
    'ARTICLE_TAGS' => 'Теги'
];
