<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ARTICLE_CAT_ID' => 'Category ID',
    'ARTICLE_CREATED_TIME' => 'Created time',
    'ARTICLE_CREATED_USER_ID' => 'Created user ID',
    'ARTICLE_FEATURED' => 'Featured',
    'ARTICLE_FULLTEXT' => 'Fulltext',
    'ARTICLE_HITS' => 'Hits',
    'ID' => 'ID',
    'ARTICLE_IMAGES' => 'Images',
    'ARTICLE_INTROTEXT' => 'Introtext',
    'ARTICLE_LANGUAGE' => 'Language',
    'ARTICLE_METADATA' => 'Metadata',
    'ARTICLE_MODIFIED_TIME' => 'Modified time',
    'ARTICLE_MODIFIED_USER_ID' => 'Modified user ID',
    'ARTICLE_ORDERING' => 'Ordering',
    'ARTICLE_PATH' => 'Path',
    'ARTICLE_PUBLISHED' => 'Published',
    'ARTICLE_TITLE' => 'Title',
];
