<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    
    'ACTIVITY_KIND' => 'Вид деятельности',
    'ADDITIONAL_EQUIPMENT' => 'Дополнительное оборудование',
    'ADDITIONAL_FILES' => 'Прикреплённые файлы',
    'ADDRESS' => 'Адрес',
    'ALIAS' => 'Псевдоним',
    'BRANCHES' => 'Филиал',
    'CATEGORY_ID' => 'Категория',
    'CATEGORY_SELECT_PARENT' => 'Выберите категорию ...',
    'CODE' => 'Артикул',
    'CONTACT_PERSON' => 'Контактное лицо',
    'CREATED_TIME' => 'Дата создания',
    'CREATED_USER_ID' => 'Создатель',
    'DESCRIPTION' => 'Описание',
    'FEATURED' => 'Избранное',
    'FULLNAME' => 'Полное наименование',
    'HITS' => 'Просмотры',
    'ID' => 'ID',
    'IMAGES' => 'Изображения',
    'LANGUAGE' => 'Язык',
    'LOGO' => 'Логотип',
    'MAIL' => 'Почта',
    'MANUFACTURER_ID' => 'Изготовитель',
    'MANUFACTURER_LINK' => 'Ссылка на изготовителя',
    'MANUFACTURER_SELECT' => 'Выберите производителя ...',
    'METADATA' => 'Метаданные',
    'MODIFIED_TIME' => 'Время изменения',
    'MODIFIED_USER_ID' => 'Изменил',
    'ORDERING' => 'Заказ',
    'PARENT_ERROR' => 'Ошибка определения категории',
    'PARENT_ID' => 'Родительская группа',
    'PHONE' => 'Телефон',
    'PUBLISHED' => 'Опубликовано',
    'SHORTNAME' => 'Короткое наименование',
    'SITE' => 'Сайт',
    'SOCIAL_NETWORKS' => 'Социальные сети',
    'SPECIFICATIONS' => 'Спецификация',
    'TITLE' => 'Заголовок',
    'VIDEO_LINK' => 'Видео',

];
