<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ALIAS' => 'Псевдоним',
    'SURE_TO_DELETE' => 'Вы уверены, что хотите удалить эту запись?',
    'CAT_ID' => 'Категория',
    'CREATE_JOURNAL' => 'Создать запись в журнале',
    'CREATE_KNOWLEDGE_BASE' => 'Создать статью',
    'CREATE_KNOWLEDGE_BASE_CATEGORY' => 'Создать категорию базы знаний',
    'CREATED_TIME' => 'Время создания',
    'CREATED_USER_ID' => 'Создал',
    'DATE' => 'Дата',
    'DELETE' => 'Удалить',
    'DESCRIPTION' => 'Описание',
    'FEATURED' => 'Избранное',
    'FULLTEXT' => 'Полный текст',
    'HITS' => 'Просмотры',
    'ID' => 'ID',
    'IMAGE' => 'Изображение',
    'IMAGES' => 'Изображения',
    'INTROTEXT' => 'Анонс',
    'JOURNALS' => 'Журналы',
    'KNOWLEDGE_BASE_CATEGORIES' => 'Категории',
    'KNOWLEDGE_BASES' => 'Статьи',
    'LANGUAGE' => 'Язык',
    'LEVEL' => 'Вложенность',
    'METADATA' => 'Метаданные',
    'MODIFIED_TIME' => 'Время изменения',
    'MODIFIED_USER_ID' => 'Изменил',
    'ORDERING' => 'Заказ',
    'PARAMS' => 'Параметры',
    'PARENT_ID' => 'Родительская категория',
    'PATH' => 'Путь',
    'PUBLISHED' => 'Опубликовано',
    'RESET' => 'Сбросить',
    'SAVE' => 'Сохранить',
    'SEARCH' => 'Поиск',
    'PAGE_DOES_NOT_EXIST' => 'Запрашиваемая страница не существует.',
    'TITLE' => 'Заголовок',
    'UPDATE' => 'Обновить',
    'UPDATE_JOURNAL' => 'Обновить запись в журнале: {name}',
    'UPDATE_KNOWLEDGE_BASE_CATEGORY' => 'Обновить категорию базы знаний: {name}',
    'UPDATE_KNOWLEDGE_BASE' => 'Обновить статью базы знаний: {name}',
];
