<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'MENU_CREATED_TIME' => 'Created time',
    'MENU_CREATED_USER_ID' => 'Created user ID',
    'ID' => 'ID',
    'MENU_LANGUAGE' => 'Language',
    'MENU_MODIFIED_TIME' => 'Modified time',
    'MENU_MODIFIED_USER_ID' => 'Modified user ID',
    'MENU_PUBLISHED' => 'Published',
    'MENU_TITLE' => 'Title',
    'MENU_PAGE_TITLE' => 'Menu',
    'MENU_PAGE_CREATE' => 'Create menu',
    'MENU_PAGE_UPDATE' => 'Update menu',
    'MENU_LINK_MENU_ID' => 'Menu',
    'MENU_LINK_LINK' => 'Link',
    'MENU_LINK_LINKS' => 'Links',
    'MENU_LINK_PARENT' => 'Parent',
    'MENU_LINK_CREATE' => 'Create link',
    'MENU_LINK_SELECT_PARENT' => 'Select parent link ...',
    'MENU_LINK_ADD_MORE_LINK' => 'Add another link',
    'MENU_LINK_LINK_LIST' => 'List of links',
];
