<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'NAV_MENU' => 'Меню',
    'NAV_USERS' => 'Пользователи',
    'NAV_USERS_LIST' => 'Список пользователей',
    'NAV_USERS_ACCESS' => 'Управление доступами',
    'NAV_USERS_ROLES' => 'Управление ролями',
    'NAV_MATERIAL_ARTICLE' => 'Статьи',
    'NAV_MATERIAL_TAGS' => 'Тэги',
    'NAV_MENU_LIST' => 'Список меню',
    'MODULE_USERS_TITLE' => 'Пользователи',
    'MODULE_USERS_CREATE' => 'Создать пользователя',
    'MODULE_USERS_STATUS_DELETE' => 'Блок',
    'MODULE_USERS_STATUS_ACTIVE' => 'Активен',
    'MODULE_USERS_LABEL_STATUS' => 'Статус',
    'MODULE_USERS_LABEL_CREATED' => 'Создан',
    'NAV_MATERIAL' => 'Контент',
    'NAV_MATERIAL_CATEGORY' => 'Категории',
    'Administration' => '',
    'SAVE' => 'Сохранить',
    'YES' => 'Да',
    'NO' => 'Нет',
    'UPDATE' => 'Изменить',
    'DELETE' => 'Удалить',
    'CREATE' => 'Создать',
    'ROOT' => 'Корень',
    'ALL' => 'Любой',
    'RU' => 'Рус',
    'EN' => 'Анг',
    'TITLE' => 'Название',
];
