<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'NAV_BASE' => 'База знаний',
    'NAV_BASE_CATEGORY' => 'Категории',
    'NAV_BASE_ARTICLES' => 'Статьи',
    'NAV_BASE_JOURNAL' => 'Журнал',
    'NAV_MENU' => 'Меню',
    'NAV_USERS' => 'Пользователи',
    'NAV_USERS_LIST' => 'Список пользователей',
    'NAV_USERS_ACCESS' => 'Управление доступами',
    'NAV_USERS_ROLES' => 'Управление ролями',
    'NAV_MATERIAL_ARTICLE' => 'Статьи',
    'NAV_MATERIAL_TAGS' => 'Тэги',
    'NAV_MENU_LIST' => 'Список меню',
    'MODULE_USERS_TITLE' => 'Пользователи',
    'MODULE_USERS_CREATE' => 'Создать пользователя',
    'MODULE_USERS_STATUS_DELETE' => 'Блок',
    'MODULE_USERS_STATUS_ACTIVE' => 'Активен',
    'MODULE_USERS_LABEL_STATUS' => 'Статус',
    'MODULE_USERS_LABEL_CREATED' => 'Создан',
    'NAV_MATERIAL' => 'Контент',
    'NAV_MATERIAL_CATEGORY' => 'Категории',
    'NAV_SETTINGS' => 'Настройки',
    
    'NAV_CATALOG' => 'Каталог',
    'NAV_PRODUCTS_MANUFACTURERS' => 'Производители',
    'NAV_PRODUCTS_CATEGORY' => 'Категории',
    'NAV_PRODUCTS_PRODUCT' => 'Продукты',
    
    'SETTINGS_SYS_TITLE' => 'Название сайта',
    'SETTINGS_SYS_STATE' => 'Состояние системы',
    'SETTINGS_SYS_SLOGAN' => 'Слоган',
    'SETTINGS_SYS_DESCRIPTION' => 'Описание сайта',
    'SETTINGS_SYS_LOGO' => 'Логотип',
    'SETTINGS_SYS_FOOTER' => 'Футер',
    'SETTINGS_ADM_MAIL' => 'Почта администратора',
    'SETTINGS_SEO_DESCRIPTION' => 'Описание для SEO',
    'SETTINGS_SEO_KEYWORDS' => 'Ключевые слова для SEO',
    
    'Administration' => '',
    'SAVE' => 'Сохранить',
    'YES' => 'Да',
    'NO' => 'Нет',
    'VIEW' => 'Просмотреть',
    'UPDATE' => 'Изменить',
    'DELETE' => 'Удалить',
    'CREATE' => 'Создать',
    'ROOT' => 'Корень',
    'ALL' => 'Любой',
    'RU' => 'Рус',
    'EN' => 'Анг',
    'TAG_TITLE' => 'Название',
];
